---
name: Hello world
description: Hello world description
outputs:
  actions-path:
    description: Actions repo root full path
    value: ${{ steps.get-path.outputs.path }}
runs:
  using: composite
  steps:
    - id: get-path
      shell: bash
      run: |
        path="$(realpath ${{ github.action_path }}/..)"
        echo "path=${path}" >> ${GITHUB_OUTPUT}
