---
name: Hello world
description: Hello world description
inputs:
  bool-input:
    description: Some input
    required: true
outputs:
  actions-path:
    description: Actions repo root full path
    value: ${{ steps.get-path.outputs.path }}
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        : bool-input=${{ inputs.bool-input }}
    - shell: bash
      if: inputs.bool-input
      run: |
        : truthy
    - shell: bash
      if: ${{ !inputs.bool-input }}
      run: |
        : falsey
    - shell: bash
      run: |
        : ${{ inputs.bool-input && 'truthy' || 'falsey' }}
