---
name: Hello world
description: Hello world description
inputs:
  run:
    description: Arbitrary command to run
    default: 'true'
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        : arbitrary command to run
        ${{ inputs.run }}

