# frozen_string_literal: true

source 'https://rubygems.org'

gem 'yabeda-karafka-2', '< 0.12.0'
gem 'karafka', '2.4.3'
gem 'karafka-core', '2.4.3'
gem 'karafka-rdkafka', '0.16.0'
gem 'karafka-testing', '2.4.6'
gem 'waterdrop', '2.7.3'
