name: Debug arm runners
on:
  workflow_dispatch:
  push:
    paths: .github/workflows/debug_arm_runners.yml
jobs:
  debug_context:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Dump github context
        run: |
          echo "$GITHUB_CONTEXT" | jq '.token = (.token[0:5] + " ...")' > context.json
          echo "$GITHUB_CONTEXT" | jq -C '.token = (.token[0:5] + " ...")'
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          
      - name: Dump github event
        run: |
          cat "$GITHUB_EVENT_PATH" > event.json
          cat "$GITHUB_EVENT_PATH" | jq -C

      - name: Dump env
        run: env | tee github_env.env

      - run: apt update -y
      - run: >-
          apt install -y
          cowsay
          $( [[ "$RUNNER_ARCH" =~ "ARM64" ]] && "tree" || "" )

      - run: |
          echo "$RUNNER_ARCH"
          echo "${{ env.RUNNER_ARCH }}"
          echo "${{ env['RUNNER_ARCH'] }}"
          echo "RUNNER_ARCH=$RUNNER_ARCH" >> "$GITHUB_ENV"
          echo "$RUNNER_ARCH"
          echo "${{ env.RUNNER_ARCH }}"
          echo "${{ env['RUNNER_ARCH'] }}"
      - run: |
          echo "$RUNNER_ARCH"
          echo "${{ env.RUNNER_ARCH }}"
          echo "${{ env['RUNNER_ARCH'] }}"

      - name: Dump github context (javascript)
        uses: actions/github-script@v7
        with:
          script: |
            console.log('inputs:', { ...context.payload.inputs })
            console.log('context:', context)

            const fs = require('fs')
            fs.writeFile(`${process.env.GITHUB_WORKSPACE}/js-context.json`, JSON.stringify(context), err => {
              if (err) {
                console.error(err);
              } else {
                console.log("File written successfuly!");
              }
            });

      - name: Dump github context (javascript & jq)
        run: cat js-context.json | jq -C

      - name: Upload github context
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            context.json
            github_env.env
            event.json
            js-context.json
