name: Debug apt
run-name: Debug apt (${{ github.event_name }})
on:
  workflow_dispatch:
  push:
    paths: .github/workflows/debug_apt.yml
jobs:
  test_rgeo:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - run: sudo apt install -qq -y --no-install-recommends libproj-dev
      - run: gem install rgeo rgeo-proj4
          
      # - run: gem install rgeo
      #   continue-on-error: true
      # - run: gem install rgeo-proj4
      #   continue-on-error: true
        
      # - run: sudo apt install -y libgeos-dev # libproj-dev proj-bin
      # - run: gem install rgeo
      #   continue-on-error: true
      # - run: gem install rgeo-proj4
      #   continue-on-error: true
        
      # - run: sudo apt install -y libproj-dev #  proj-bin
      # - run: gem install rgeo
      #   continue-on-error: true
      # - run: gem install rgeo-proj4
      #   continue-on-error: true
        
      # - run: sudo apt install -y proj-bin
      # - run: gem install rgeo
      #   continue-on-error: true
      # - run: gem install rgeo-proj4
      #   continue-on-error: true
  test_caching:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libproj-dev
          version: v1
      - run: gem install rgeo rgeo-proj4
  test_hot_cache:
    needs: test_caching
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libproj-dev
          version: v1
      - run: gem install rgeo rgeo-proj4
