name: Debug matrix env/context
run-name: Debug matrix (${{ github.event_name }})
on:
  workflow_dispatch:
jobs:
  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [0, 1, 2, 3]
    steps:
      - name: Dump github context
        run: echo "$MATRIX_CONTEXT" | jq '.token = "***"' | tee github_context.json
        shell: bash
        env:
          MATRIX_CONTEXT: ${{ toJson(github) }}
      - name: Dump matrix context
        run: echo "$MATRIX_CONTEXT" tee matrix_context.json
        shell: bash
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
      - name: Dump strategy context
        run: echo "$STRATEGY_CONTEXT" | tee strategy_context.json
        shell: bash
        env:
          MATRIX_CONTEXT: ${{ toJson(strategy) }}
      - name: Dump env
        run: env | tee github_env.env
      - name: Dump github context (javascript)
        uses: actions/github-script@v7
        with:
          script: |
            console.log('inputs:', { ...context.payload.inputs })
            console.log('context:', context)
      - name: Upload github context
        uses: actions/upload-artifact@v4
        with:
          name: matrix-artifacts-${{ strategy.job-index }}
          path: |
            github_context.json
            matrix_context.json
            strategy_context.json
            github_env.env
  test_post_matrix:
    runs-on: ubuntu-latest
    needs: [test_matrix]
    steps:
      - name: Dump needs context
        run: echo "$NEEDS_CONTEXT" tee needs_context.json
        shell: bash
        env:
          NEEDS_CONTEXT: ${{ toJson(needs) }}
      - name: Dump needs.*.result context
        run: echo "$NEEDS_RESULT_CONTEXT" tee needs_result_context.json
        shell: bash
        env:
          NEEDS_RESULT_CONTEXT: ${{ toJson(needs.*.result) }}
      - name: Debug interpolation of needs.*.result (1)
        continue-on-error: true
        run: echo ${{ needs.*.result }}
      - name: Debug interpolation of needs.*.result (2)
        continue-on-error: true
        run: echo ${{ needs.*.result }}
      - name: Debug interpolation of needs.*.result (3)
        continue-on-error: true
        run: echo "$NEEDS_RESULT_CONTEXT"
        env:
          NEEDS_RESULT_CONTEXT: ${{ needs.*.result }}
      - name: Debug interpolation of needs.*.result (4)
        continue-on-error: true
        run: echo "$NEEDS_RESULT_CONTEXT"
        env:
          NEEDS_RESULT_CONTEXT: ${{ toJson(needs.*.result) }}
