---
name: Debug arbitrary commands
on:
  push:
    paths: .github/workflows/debug_arbitrary_commands.yml
jobs:
  debug_other_workflow:
    uses: ./.github/workflows/debug_context.yml
    with:
      environment: ${{ github.event.inputs.my_env }}
      noop: false
      arbitrary: whatever
      other_param: 'fooooo'
      run: |
        env
        echo "Hello world"
  debug_other_composite_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Drowze/ci-testing/action-arbitrary-run-command@master
        with:
          run: |
            env
            echo "Hello world"
  debug_stderr:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ruby -e '$stderr.puts "something went wrong\nlololo\nmultiline!!!!"; exit 1' 2> $RUNNER_TEMP/stderr.out || error_code="$?"
          if [ -n "$error_code" ]; then
            error="$(cat $RUNNER_TEMP/stderr.out)"
            echo "opa 1"
            echo "::error title=Script failed::${error}"
            echo "opa 2"
            echo exit "$error_code"
            exit "$error_code"
          fi
