name: Debug create pr
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/debug_create_pr.yml
jobs:
  debug_create_pr:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: commit-push
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ format('{0}+{1}@users.noreply.github.com', github.actor_id, github.actor) }}
          branch="debug-create-pr-$(dd if=/dev/urandom bs=15 count=1 status=none | sha256sum | head -c 6)"
          echo "branch=${branch}" >> $GITHUB_OUTPUT
          git switch --create "$branch"
          echo "$branch" >> README.md
          git commit -am "Debug create PR ${branch}"
          git push origin ${branch}
      - name: Create pull request
        run: |
          result="$(gh pr create --title "Debug create PR" --body 'Debugging creating PR' --draft 2>&1 | tail -n1)"
          echo "---- created_pr_result: ----"
          echo "$result"
          echo "---------------------------"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Create pull request (when it already exists)
        run: |
          result="$(gh pr create --title "Debug create PR" --body 'Debugging creating PR' --draft 2>&1 | tail -n1)"
          echo "---------------------------"
          echo "- pr_already_exist_result -"
          echo "$result"
          echo "---------------------------"
