name: Test pull request creation

on:
  workflow_dispatch:

jobs:
  test-pr-creation:
    name: Create PR with foo file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create file
        run: date > foo.txt

      - run: git fetch origin automation-create-foo-pr
      - run: git show-ref
      - run: git ls-remote
      - run: git remote -v

      - name: Create/update PR with changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: '[auto] Test PR creation'
          base: ${{ github.event.repository.default_branch }}
          branch: automation-create-foo-pr
          title: 'Test pull request'
          assignees: Drowze
          body: |
            Created by Github Action.

            Log: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}

      # - name: Create automated pull request
      #   run: |
      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git config user.name "github-actions[bot]"

      #     git fetch origin "${HEAD_BRANCH}" || true
      #     existing_pr="$(gh pr view "${HEAD_BRANCH}" --json 'state,url' 2>/dev/null || true)"

      #     # error out if:
      #     # - there is a pull request in OPEN state for this commit
      #     # - AND last committer was NOT a bot
      #     if [ "$(echo "${existing_pr}" | jq -r '.state')" == "OPEN" ]; then
      #       author="$(git log -n1 origin/"${HEAD_BRANCH}" --format=format:'%an')"
      #       if [ "$author" != "github-actions[bot]" ]; then
      #         echo "::error title=Could not create PR - there is already an open PR that has been manually managed."
      #         exit 1
      #       fi
      #     fi

      #     git switch --force-create "${HEAD_BRANCH}"
      #     git add ${FILES_TO_COMMIT}
      #     git commit --message "${COMMIT_MESSAGE}"
      #     git push --force-with-lease origin "${HEAD_BRANCH}"

      #     echo "${existing_pr}"
      #     echo "${existing_pr}" | jq '.state'
      #     [[ "$(echo "${existing_pr}" | jq -r '.state')" == "OPEN" ]] && echo true || echo false

      #     if [ "$(echo "${existing_pr}" | jq -r '.state')" == "OPEN" ]; then
      #       url="$(echo "${existing_pr}" | jq -r '.url')"
      #       echo "### Pull request updated: ${url}" >> $GITHUB_STEP_SUMMARY
      #     else
      #       url="$(gh pr create -B "${BASE_BRANCH}" -H "${HEAD_BRANCH}" --title "${PR_TITLE}" --body "${PR_BODY}")"
      #       echo "### Pull request created: ${url}" >> $GITHUB_STEP_SUMMARY
      #     fi
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      #     FILES_TO_COMMIT: foo.txt
      #     BASE_BRANCH: ${{ github.event.repository.default_branch }}
      #     HEAD_BRANCH: automation-create-foo-pr
      #     COMMIT_MESSAGE: '[auto] Test PR creation'
      #     PR_TITLE: 'Test pull request'
      #     PR_BODY: |
      #       Created by Github action.

      #       Log: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
