name: Test pull request creation

on:
  workflow_dispatch:

jobs:
  test-pr-creation:
    name: Create PR with foo file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: |
          touch foo.txt
          # git switch --force-create automation-create-foo-pr
          git add foo.txt
          # git commit -m "[auto] Test PR creation"
          # git push origin automation-create-foo-pr
          gh pr create -B master -H automation-create-foo-pr --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
