name: Test pull request creation

on:
  workflow_dispatch:

jobs:
  test-pr-creation:
    name: Create PR with foo file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create file
        run: date > foo.txt

      - name: Create automated pull request
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          git log -n1 origin/"${BRANCH}"

          git switch --force-create ${BRANCH}
          git add ${FILES_TO_COMMIT}
          git commit -m "${COMMIT_MESSAGE}"
          
          if ! gh pr create -B "${BASE_BRANCH}" -H "${BRANCH}" --title "${PR_TITLE}" --body "${PR_BODY}"; then
            # PR already exists; check if it's safe then force-push
            git log
            git fetch
            git log
          fi
        env:
          FILES_TO_COMMIT: foo.txt
          BASE_BRANCH: ${{ github.event.repository.default_branch }}
          HEAD_BRANCH: automation-create-foo-pr
          COMMIT_MESSAGE: '[auto] Test PR creation'
          PR_TITLE: 'Test pull request'
          PR_BODY: |
            Created by Github action.

            Log: ${{ github.event.repository.http_url }}/actions/runs/${{ github.run_id }}
